apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-examples
  description: Description of the terraform-examples repository
  annotations:
    github.com/project-slug: ankkitraj/terraform-examples
spec:
  type: service
  owner: ankkitraj
  lifecycle: production
  system: my-system
  links:
    - url: https://github.com/ankkitraj/terraform-examples
      title: Repository
